# Generated by Django 4.2.1 on 2023-05-31 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_tag_remove_todo_name_todo_description_todo_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
